#
# /etc/doas.conf
#

permit persist :sudo
permit nopass :adm as root cmd /bin/dmesg
permit nopass :adm as root cmd /bin/apt-get args autoclean
permit nopass :adm as root cmd /bin/apt-get args clean
permit nopass :adm as root cmd /bin/apt-get args update
permit nopass :adm as root cmd /bin/apt-get args -y autoremove --purge
permit nopass :adm as root cmd /bin/apt-get args -y dist-upgrade
