#!/bin/sh

#
# ~/local/bin/calc_bat
#

SYSP=/sys/class/power_supply
BATT=sbs-104-000b
FILE=~/.batt
STAT=$(cat $SYSP/$BATT/status)
TTEAS=$(cat $SYSP/$BATT/time_to_empty_avg)
TTFAS=$(cat $SYSP/$BATT/time_to_full_avg)

div_60 () {
  return $(expr $1 / 60)
}

mod_60 () {
  return $(expr $1 % 60)
}


case "$STAT" in
  "Full")
    echo '☻ FULL' > $FILE
    ;;
  "Discharging")
    div_60 $TTEAS
    MINT=$?
    div_60 $MINT
    HOURS=$?
    mod_60 $MINT
    MINR=`printf %02d $?`

    echo "🔋 $HOURS:$MINR rem" > $FILE
    ;;
  "Charging")
    div_60 $TTFAS
    MINT=$?
    div_60 $MINT
    HOURS=$?
    mod_60 $MINT
    MINR=`printf %02d $?`

    echo "⚡ $HOURS:$MINR chr" > $FILE
    ;;
  *)
    echo "No battery" > $FILE
    ;;
esac
exit 0
